version: '3.8'
services:
  backend:
    build: .
    container_name: web-backend
    ports:
      - "8081:8000"
    environment:
      - PORT=8000

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: http://localhost:8081
    container_name: web-frontend
    ports:
      - "8082:3000"
    depends_on:
      - backend
